name = "hxsf-casper"
license = "MIT"
licenselink = "https://github.com/hxsf/casper/blob/master/LICENSE"
description = "My Casper theme from Ghost CMS ported over to Hugo"
tags = ["blog", "dark", "light"]
features = ["darkmode"]
min_version = "0.54.0"

[author]
  name = "Jonathan Janssens"
  homepage = "https://jonathanjanssens.com"
  repo = "https://github.com/jonathanjanssens/projects/hugo-casper3"

[original]
  name = "Ghost"
  homepage = "https://ghost.org"
  repo = "https://github.com/TryGhost/Casper"

  