baseURL = "http://blog.hxsf.me/"
disablePathToLower = true
languageCode = "zh-cn"
background = "aa"
title = "Who am I"
summaryLength = 100
hasCJKLanguage = true
theme = "hugo-casper3"

[params]
feature_image = "https://static.hxsf.me/images/2015/07/hello-world.jpg-webp"